"""initial

Revision ID: 2fe5251b1a6c
Revises: 
Create Date: 2026-06-11 08:16:10.099283
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2fe5251b1a6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('google_sub', sa.String(length=128), nullable=False, comment='Google OAuth2 subject Id - universal key across web and Android'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('bmr', sa.Float(), nullable=True, comment='Mifflin-St Jeor BMR (kcal/day)'),
    sa.Column('bmi', sa.Float(), nullable=True, comment='Body Mass Index'),
    sa.Column('character_class', sa.Enum('NOVICE', 'WARRIOR', 'RANGER', 'MAGE', name='characterclass'), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False, comment='The calendar day this activity belongs to (used for daily grouping)'),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False, comment='When the entry was actually created in the system'),
    sa.Column('source', sa.Enum('VOICE', 'HEALTH_CONNECT', 'MANUAL', name='activitysource'), nullable=False),
    sa.Column('exercise_type', sa.Enum('RUN', 'WALK', 'CYCLE', 'SWIM', 'HIKE', 'LIFT', 'YOGA', 'PILATES', 'HIIT', 'STRETCH', 'SPORT', 'OTHER', name='exercisetype'), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('reps_count', sa.Integer(), nullable=True),
    sa.Column('sets_count', sa.Integer(), nullable=True),
    sa.Column('weight_lifted_kg', sa.Float(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('heart_rate_zone', sa.Enum('REST', 'FAT_BURN', 'CARDIO', 'PEAK', name='heartratezone'), nullable=True),
    sa.Column('water_ml', sa.Integer(), nullable=True),
    sa.Column('calories_consumed', sa.Integer(), nullable=True),
    sa.Column('meal_description', sa.String(length=300), nullable=True),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_score', sa.Integer(), nullable=True),
    sa.Column('hc_record_id', sa.String(length=128), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hc_record_id')
    )
    op.create_index(op.f('ix_activity_logs_log_date'), 'activity_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('character_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='The calender day this snapshot represents'),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('endurance', sa.Float(), nullable=False),
    sa.Column('vitality', sa.Float(), nullable=False),
    sa.Column('agility', sa.Float(), nullable=False),
    sa.Column('recovery', sa.Float(), nullable=False),
    sa.Column('discipline', sa.Float(), nullable=False),
    sa.Column('daily_xp_earned', sa.Integer(), nullable=False),
    sa.Column('cumulative_xp', sa.Integer(), nullable=False),
    sa.Column('level_at_snapshot', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('total_active_minutes', sa.Integer(), nullable=False),
    sa.Column('total_calories_burned', sa.Integer(), nullable=False),
    sa.Column('total_water_ml', sa.Integer(), nullable=False),
    sa.Column('avg_heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stat_date', name='uq_character_stats_user_date')
    )
    op.create_index(op.f('ix_character_stats_stat_date'), 'character_stats', ['stat_date'], unique=False)
    op.create_index(op.f('ix_character_stats_user_id'), 'character_stats', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When the access_token expires — refresh before this time'),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_character_stats_user_id'), table_name='character_stats')
    op.drop_index(op.f('ix_character_stats_stat_date'), table_name='character_stats')
    op.drop_table('character_stats')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_log_date'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###